#!/usr/bin/env python3
"""Regenerate the committed seed network (network/).

The seed network is the network's founding story made visible: a handful of
public branches (no private keys — these are PublicStates, verifiable by
anyone) with real forks, an accepted idea, a replaceability block, and a
crystallized branch that sealed itself.

Every branch is generated by the real protocol (init/fork/amend/adopt/seal),
then its private key is stripped. What remains is what any peer would see:
APP.md, RULES.md, INSTITUTIONS.md, DECISIONS.jsonl, EVENTS.jsonl.

    python examples/seed_network.py [--out network]

The script owns the output directory completely — it is regenerated from
scratch each run (node ids change; the story does not).
"""

import argparse
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from adaptive_pluralism_protocol.protocol_node import (  # noqa: E402
    ProtocolNode,
    init_node,
)


PUBLIC_FILES = ("APP.md", "RULES.md", "INSTITUTIONS.md", "DECISIONS.jsonl", "EVENTS.jsonl")


def strip_to_public(node: ProtocolNode):
    app_dir = node.dir / ".app"
    if app_dir.exists():
        shutil.rmtree(app_dir)
    for fname in ("APP.md", "RULES.md", "INSTITUTIONS.md", "DECISIONS.jsonl"):
        assert (node.dir / fname).exists(), f"missing {fname}"


def audit_line(node: ProtocolNode) -> str:
    audits = [d for d in node.decisions() if d["kind"] == "audit"]
    if not audits:
        return "no audit yet"
    a = audits[-1]["audit"]
    status = a.get("status", "-")
    return f"{a.get('scenario', '?')} -> {status}  R={a.get('R')}"


def fork_named(parent: ProtocolNode, out: Path, name: str, statement: str) -> ProtocolNode:
    """Fork and give the child its own name (the ledger, not APP.md, is law)."""
    child = parent.fork(out, statement)
    lines = []
    for line in (out / "APP.md").read_text().splitlines():
        if line.startswith("name:"):
            lines.append(f"name: {name}")
        else:
            lines.append(line)
    (out / "APP.md").write_text("\n".join(lines) + "\n")
    return ProtocolNode(out)


def main():
    p = argparse.ArgumentParser(description="regenerate the committed seed network")
    p.add_argument("--out", default="network")
    args = p.parse_args()

    root = Path(args.out)
    if root.exists():
        shutil.rmtree(root)

    # ── the founding branch ────────────────────────────────────────────
    genesis = init_node(root / "0penAGI", "0penAGI")
    genesis.pulse("the founding branch crash-tests its own laws")

    # ── two independent forks of the founding branch ───────────────────
    eliza = fork_named(genesis, root / "eliza", "eliza",
                       "the alignment premise must be stress-tested")
    eliza.add_institution("Alignment_Registry", "track AGI failure evidence",
                          replaceable="yes", replace_with="Community_Verdicts")
    eliza.amend_rules({"hostile_agi": "yes", "agi_at": "8"},
                      "assume hostile AGI until proven otherwise")

    commons = fork_named(genesis, root / "commons", "commons",
                         "build the immune architecture first")
    commons.add_institution("Commons_Trust", "commons",
                            replaceable="yes", replace_with="Mutual_Guarantee")
    commons.add_institution("City_Network", "infrastructure",
                            replaceable="yes", replace_with="Commons_Trust")
    commons.pulse("immune architecture under routine pressure")

    # ── a branch that learns and then retires in favor of its child ────
    eliza_v2 = fork_named(eliza, root / "eliza-v2", "eliza-v2",
                          "shorter audit period: check the meters more often")
    eliza_v2.amend_rules({"audit_period": "2"}, "tighten the audit loop")
    eliza.seal("the premise branch is superseded by eliza-v2", superseded_by=eliza_v2.node_id)
    eliza_v2.pulse("tightened audit loop under hostile pressure")

    # ── an accepted idea: commons adopts eliza-v2's premise ────────────
    adopted = commons.adopt(eliza_v2.dir, eliza_v2.last_decision()["id"],
                            "accept the hostile-AGI premise from eliza-v2")
    commons.pulse("accepted idea crash-tested")

    # ── a branch with a real replaceability block ──────────────────────
    guardian = fork_named(commons, root / "guardian", "guardian",
                          "watch the immune system itself")
    guardian.add_institution("The_Leviathan", "governance",
                             replaceable="no", replace_with="")
    guardian.pulse("a non-replaceable institution is a live risk, not a rule")

    # ── a crystallized branch that sealed itself ───────────────────────
    old_order = fork_named(genesis, root / "old-order", "old-order",
                           "the old order: no immunity, no exit")
    old_order.amend_rules({"self_immunity": "no", "hostile_agi": "yes"},
                          "immunity is a cost, not a property")
    report = old_order.pulse("the old order crash-tests its own rigidity")
    old_order.seal("this branch crystallized; it retires itself by its own laws")

    # ── strip private keys: commit only the verifiable public states ───
    summary = []
    for name in ("0penAGI", "eliza", "eliza-v2", "commons", "guardian", "old-order"):
        node = ProtocolNode(root / name)
        problems = node.verify_chain()
        summary.append((node.node_id, name, audit_line(node),
                        node.status()["sealed"], "ok" if not problems else f"FAIL: {problems}"))
        strip_to_public(node)

    print("seed network regenerated — every ledger verified:")
    for node_id, name, audit, sealed, tag in summary:
        seal_tag = "  SEALED" if sealed else ""
        print(f"  {node_id}  {name:10} {audit}{seal_tag}   [{tag}]")


if __name__ == "__main__":
    main()
